services:
  php:
    build:
      context: .
      dockerfile: Dockerfile
      target: dev
    volumes:
      - ".:/opt/app"
    depends_on:
      mariadb:
        condition: service_healthy
    links:
      - mariadb
    networks:
      - symfony-local-dev
    env_file:
      - .env.compose
  mariadb:
    image: mariadb:10
    ports:
      - 127.0.0.1:13306:3306
    volumes:
      - mariadb-data:/var/lib/mysql:delegated
    networks:
      - symfony-local-dev
    healthcheck:
      test: [ "CMD", "healthcheck.sh", "--connect", "--innodb_initialized" ]
      start_period: 1m
      start_interval: 10s
      interval: 1m
      timeout: 5s
      retries: 3
    env_file:
      - .env.compose
  nginx:
    image: nginx:1.19.6
    ports:
      - 127.0.0.1:8090:80
    volumes:
      - ".docker/nginx/templates:/etc/nginx/templates:delegated"
    links:
      - php
    depends_on:
      php:
        condition: service_started
    networks:
      - symfony-local-dev
    env_file:
      - .env.compose

networks:
  symfony-local-dev:

volumes:
  mariadb-data:
